# Form implementation generated from reading ui file 'ui_qt6_file/ui_DialogConfigAcctionTiktok.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json
import utils
class ui_ConfigAcctionTiktok(object):
    def setupUi(self, DialogConfigAcctionTiktok):
        DialogConfigAcctionTiktok.setObjectName("DialogConfigAcctionTiktok")
        DialogConfigAcctionTiktok.resize(543, 788)
        DialogConfigAcctionTiktok.setStyleSheet("background-color: #121212    ")
        self.configTiktokGroupBox = QtWidgets.QGroupBox(parent=DialogConfigAcctionTiktok)
        self.configTiktokGroupBox.setGeometry(QtCore.QRect(10, 10, 521, 781))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.configTiktokGroupBox.setFont(font)
        self.configTiktokGroupBox.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.configTiktokGroupBox.setObjectName("configTiktokGroupBox")
        self.label = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listActionComboBox = QtWidgets.QComboBox(parent=self.configTiktokGroupBox)
        self.listActionComboBox.setGeometry(QtCore.QRect(160, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listActionComboBox.setFont(font)
        self.listActionComboBox.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.listActionComboBox.setObjectName("listActionComboBox")
        self.listActionComboBox.addItem("")
        self.listActionComboBox.addItem("")
        self.listActionComboBox.addItem("")
        self.listActionComboBox.addItem("")
        self.listActionComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeActionText = QtWidgets.QLineEdit(parent=self.configTiktokGroupBox)
        self.timeActionText.setGeometry(QtCore.QRect(210, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeActionText.setFont(font)
        self.timeActionText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.timeActionText.setObjectName("timeActionText")
        self.label_3 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.liveAcctionText = QtWidgets.QLineEdit(parent=self.configTiktokGroupBox)
        self.liveAcctionText.setGeometry(QtCore.QRect(210, 130, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.liveAcctionText.setFont(font)
        self.liveAcctionText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.liveAcctionText.setObjectName("liveAcctionText")
        self.followAcctionText = QtWidgets.QLineEdit(parent=self.configTiktokGroupBox)
        self.followAcctionText.setGeometry(QtCore.QRect(210, 180, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.followAcctionText.setFont(font)
        self.followAcctionText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.followAcctionText.setObjectName("followAcctionText")
        self.commentAcctionText = QtWidgets.QLineEdit(parent=self.configTiktokGroupBox)
        self.commentAcctionText.setGeometry(QtCore.QRect(210, 230, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.commentAcctionText.setFont(font)
        self.commentAcctionText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.commentAcctionText.setObjectName("commentAcctionText")
        self.label_5 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.contentCommentText = QtWidgets.QTextEdit(parent=self.configTiktokGroupBox)
        self.contentCommentText.setGeometry(QtCore.QRect(30, 320, 441, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contentCommentText.setFont(font)
        self.contentCommentText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.contentCommentText.setObjectName("contentCommentText")
        self.label_7 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 530, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.userOrBaseText = QtWidgets.QTextEdit(parent=self.configTiktokGroupBox)
        self.userOrBaseText.setGeometry(QtCore.QRect(30, 570, 441, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userOrBaseText.setFont(font)
        self.userOrBaseText.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.userOrBaseText.setObjectName("userOrBaseText")
        self.label_8 = QtWidgets.QLabel(parent=self.configTiktokGroupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 730, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.numberOfRepetitions = QtWidgets.QLineEdit(parent=self.configTiktokGroupBox)
        self.numberOfRepetitions.setGeometry(QtCore.QRect(200, 720, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberOfRepetitions.setFont(font)
        self.numberOfRepetitions.setStyleSheet("background-color:#999999    ;color:#E0E0E0;border-radius:10px")
        self.numberOfRepetitions.setObjectName("numberOfRepetitions")
        self.saveConfigBtn = QtWidgets.QPushButton(parent=self.configTiktokGroupBox)
        self.saveConfigBtn.setGeometry(QtCore.QRect(430, 20, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveConfigBtn.setFont(font)
        self.saveConfigBtn.setStyleSheet("background-color: #272727;color:#E0E0E0;")
        self.saveConfigBtn.setObjectName("saveConfigBtn")

        self.retranslateUi(DialogConfigAcctionTiktok)
        QtCore.QMetaObject.connectSlotsByName(DialogConfigAcctionTiktok)
        self.saveConfigBtn.clicked.connect(self.saveConfig)
    def saveConfig(self):
        action_name = self.listActionComboBox.currentText()
        action_map = {
            "Nuôi acc": "growAcc",
            "Tương tác newfeed": "interactNewfeed",
            "Tương tác user": "interactUser",
            "Tương tác theo chủ đề": "interactTopic",
            "Tương tác live": "interactLive"
        }
        action_key = action_map.get(action_name, "unknownAction")

        new_action_data = {
            "time": self.timeActionText.text(),
            "numberOflike": self.liveAcctionText.text(),
            "numberOffollow": self.followAcctionText.text(),
            "numberOfComment": self.commentAcctionText.text(),
            "contentOfComment": self.contentCommentText.toPlainText(),
            "usernameOrBase": self.userOrBaseText.toPlainText(),
            "repeat": self.numberOfRepetitions.text()
        }

        file_path = utils.CONFIG_ACCTION_TIKTOK

        # Load existing config data
        try:
            with open(file_path, "r") as json_file:
                config_data = json.load(json_file)
            if "actions" not in config_data:
                config_data["actions"] = []
        except FileNotFoundError:
            config_data = {"actions": []}
        except json.JSONDecodeError:
            config_data = {"actions": []}

        # Check if the action already exists and overwrite it
        action_exists = False
        for i, action in enumerate(config_data["actions"]):
            if action["nameAcction"] == action_key:
                config_data["actions"][i] = {
                    "nameAcction": action_key,
                    "listAcc": [new_action_data]
                }
                action_exists = True
                break

        # If the action does not exist, add a new entry
        if not action_exists:
            config_data["actions"].append({
                "nameAcction": action_key,
                "listAcc": [new_action_data]
            })

        # Save the updated config data back to the file
        with open(file_path, "w") as json_file:
            json.dump(config_data, json_file, ensure_ascii=False, indent=4)

        # Clear input fields after saving
        self.timeActionText.clear()
        self.liveAcctionText.clear()
        self.followAcctionText.clear()
        self.commentAcctionText.clear()
        self.contentCommentText.clear()
        self.userOrBaseText.clear()
        self.numberOfRepetitions.clear()
        self.listActionComboBox.setCurrentIndex(0)  # Optionally reset the combo box to the first item

        QtWidgets.QMessageBox.information(None, "Saved", "Lưu thành công")

    def retranslateUi(self, DialogConfigAcctionTiktok):
        _translate = QtCore.QCoreApplication.translate
        DialogConfigAcctionTiktok.setWindowTitle(_translate("DialogConfigAcctionTiktok", "Dialog"))
        self.configTiktokGroupBox.setTitle(_translate("DialogConfigAcctionTiktok", "Cấu hình tương tác"))
        self.label.setText(_translate("DialogConfigAcctionTiktok", "Chọn tương tác:"))
        self.listActionComboBox.setItemText(0, _translate("DialogConfigAcctionTiktok", "Nuôi acc"))
        self.listActionComboBox.setItemText(1, _translate("DialogConfigAcctionTiktok", "Tương tác newfeed"))
        self.listActionComboBox.setItemText(2, _translate("DialogConfigAcctionTiktok", "Tương tác user"))
        self.listActionComboBox.setItemText(3, _translate("DialogConfigAcctionTiktok", "Tương tác theo chủ đề"))
        self.listActionComboBox.setItemText(4, _translate("DialogConfigAcctionTiktok", "Tương tác live"))
        self.label_2.setText(_translate("DialogConfigAcctionTiktok", "Thời gian tương tác (s):"))
        self.label_3.setText(_translate("DialogConfigAcctionTiktok", "Số tim:"))
        self.label_4.setText(_translate("DialogConfigAcctionTiktok", "Số theo dõi:"))
        self.label_5.setText(_translate("DialogConfigAcctionTiktok", "Số bình luận:"))
        self.label_6.setText(_translate("DialogConfigAcctionTiktok", "Nội dung bình luận:"))
        self.label_7.setText(_translate("DialogConfigAcctionTiktok", "Nhập tên người dùng hoặc nội dung tương tác:"))
        self.label_8.setText(_translate("DialogConfigAcctionTiktok", "Số lần lặp lại (nếu cần):"))
        self.saveConfigBtn.setText(_translate("DialogConfigAcctionTiktok", "Lưu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogConfigAcctionTiktok = QtWidgets.QDialog()
    ui = ui_ConfigAcctionTiktok()
    ui.setupUi(DialogConfigAcctionTiktok)
    DialogConfigAcctionTiktok.show()
    sys.exit(app.exec())
