# Form implementation generated from reading ui file 'srcFE/uiFile/ui_DialogInputAccTiktok.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os 
import utils
import json
class ui_InputAccTiktok(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 524)
        Dialog.setStyleSheet("background-color: #121212    ")
        self.addAccTiktokGroupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.addAccTiktokGroupBox.setGeometry(QtCore.QRect(20, 10, 681, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addAccTiktokGroupBox.setFont(font)
        self.addAccTiktokGroupBox.setStyleSheet("color:#E0E0E0")
        self.addAccTiktokGroupBox.setObjectName("addAccTiktokGroupBox")
        self.saveAccTiktoklBtn = QtWidgets.QPushButton(parent=self.addAccTiktokGroupBox)
        self.saveAccTiktoklBtn.setGeometry(QtCore.QRect(570, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveAccTiktoklBtn.setFont(font)
        self.saveAccTiktoklBtn.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.saveAccTiktoklBtn.setObjectName("saveAccTiktoklBtn")
        self.inputAcctiktok = QtWidgets.QTextEdit(parent=self.addAccTiktokGroupBox)
        self.inputAcctiktok.setGeometry(QtCore.QRect(20, 80, 641, 401))
        self.inputAcctiktok.setStyleSheet("background-color:#999999;border-radius:10px;color:#E0E0E0")
        self.inputAcctiktok.setObjectName("inputAcctiktok")
        self.groupNameLabel = QtWidgets.QLabel(parent=self.addAccTiktokGroupBox)
        self.groupNameLabel.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupNameLabel.setFont(font)
        self.groupNameLabel.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.groupNameLabel.setObjectName("groupNameLabel")
        self.inputNameGroupAccTiktok = QtWidgets.QLineEdit(parent=self.addAccTiktokGroupBox)
        self.inputNameGroupAccTiktok.setGeometry(QtCore.QRect(150, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputNameGroupAccTiktok.setFont(font)
        self.inputNameGroupAccTiktok.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.inputNameGroupAccTiktok.setObjectName("inputNameGroupAccTiktok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.saveAccTiktoklBtn.clicked.connect(self.saveAccTiktok)
    def saveAccTiktok(self):
        group_name = self.inputNameGroupAccTiktok.text()
        acc_data = self.inputAcctiktok.toPlainText().split("\n")
        acc_list = [{"acc": ua.strip()} for ua in acc_data if ua.strip()]
        file_name = utils.ACC_TIKTOK_JSON
        if group_name and acc_list:
            # file_name, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save File", "", "JSON Files (*.json)")
            if file_name:
                if not file_name.endswith(".json"):
                    file_name += ".json"

                # Tạo thư mục đích nếu chưa tồn tại
                directory = os.path.dirname(file_name)
                if not os.path.exists(directory):
                    os.makedirs(directory)

                # Kiểm tra và đọc dữ liệu hiện có từ tệp (nếu có)
                if os.path.exists(file_name) and os.path.getsize(file_name) > 0:
                    try:
                        with open(file_name, "r") as file:
                            existing_data = json.load(file)
                    except json.JSONDecodeError:
                        existing_data = []
                else:
                    existing_data = []

                # Tạo dictionary mới cho dữ liệu mới
                new_data = {
                    "groupAcc": group_name,
                    "listAcc": acc_list
                }

                # Thêm dữ liệu mới vào danh sách dữ liệu hiện có
                existing_data.append(new_data)

                # Ghi lại danh sách dữ liệu vào tệp JSON
                with open(file_name, "w") as file:
                    json.dump(existing_data, file, indent=4, ensure_ascii=False)

                QtWidgets.QMessageBox.information(None, "Thông báo", "Dữ liệu đã được lưu thành công!")
        else:
            QtWidgets.QMessageBox.warning(None, "Cảnh báo", "Vui lòng nhập đầy đủ thông tin trước khi lưu!")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addAccTiktokGroupBox.setTitle(_translate("Dialog", "Thêm tài khoản tiktok"))
        self.saveAccTiktoklBtn.setText(_translate("Dialog", "Lưu"))
        self.groupNameLabel.setText(_translate("Dialog", "Group Name:"))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ui_InputAccTiktok()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
