# Form implementation generated from reading ui file 'srcFE/uiFile/ui_DialogInputUA.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import utils

class ui_InputUserAgent(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 531)
        Dialog.setStyleSheet("background-color: #121212    ")
        self.addUserAgentGroupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.addUserAgentGroupBox.setGeometry(QtCore.QRect(20, 20, 681, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addUserAgentGroupBox.setFont(font)
        self.addUserAgentGroupBox.setStyleSheet("color:#E0E0E0")
        self.addUserAgentGroupBox.setObjectName("addUserAgentGroupBox")
        self.saveUABtn = QtWidgets.QPushButton(parent=self.addUserAgentGroupBox)
        self.saveUABtn.setGeometry(QtCore.QRect(570, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveUABtn.setFont(font)
        self.saveUABtn.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.saveUABtn.setObjectName("saveUABtn")
        self.inputUA = QtWidgets.QTextEdit(parent=self.addUserAgentGroupBox)
        self.inputUA.setGeometry(QtCore.QRect(20, 70, 641, 411))
        self.inputUA.setStyleSheet("background-color:#999999;border-radius:10px;color:#E0E0E0")
        self.inputUA.setObjectName("inputUA")
        self.inputUA.setFont(QtGui.QFont("Arial", 12))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.saveUABtn.clicked.connect(self.saveUserAgent)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addUserAgentGroupBox.setTitle(_translate("Dialog", "Thêm user agents"))
        self.saveUABtn.setText(_translate("Dialog", "Lưu"))

    def saveUserAgent(self):
        file_name = utils.USER_AGENT_TXT
        user_agent = self.inputUA.toPlainText()
        if user_agent:
            with open(file_name, "a") as file:
                file.write(user_agent + "\n")
            QtWidgets.QMessageBox.information(None, "Thông báo", "User Agent đã được lưu thành công!")
        else:
            QtWidgets.QMessageBox.warning(None, "Cảnh báo", "Vui lòng nhập User Agent trước khi lưu!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ui_InputUserAgent()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
