# Form implementation generated from reading ui file 'srcFE/uiFile/ui_DialogInputHotmail.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json
import os
import utils
class ui_InputHotmail(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 527)
        Dialog.setStyleSheet("background-color: #121212    ")
        self.addHotmailGroupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.addHotmailGroupBox.setGeometry(QtCore.QRect(20, 10, 681, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addHotmailGroupBox.setFont(font)
        self.addHotmailGroupBox.setStyleSheet("color:#E0E0E0")
        self.addHotmailGroupBox.setObjectName("addHotmailGroupBox")
        self.saveHotmailBtn = QtWidgets.QPushButton(parent=self.addHotmailGroupBox)
        self.saveHotmailBtn.setGeometry(QtCore.QRect(570, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveHotmailBtn.setFont(font)
        self.saveHotmailBtn.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.saveHotmailBtn.setObjectName("saveHotmailBtn")
        self.inputHotmail = QtWidgets.QTextEdit(parent=self.addHotmailGroupBox)
        self.inputHotmail.setGeometry(QtCore.QRect(20, 80, 641, 401))
        self.inputHotmail.setStyleSheet("background-color:#999999;border-radius:10px;color:#E0E0E0")
        self.inputHotmail.setObjectName("inputHotmail")
        self.inputHotmail.setFont(QtGui.QFont("Arial", 12))
        self.groupNameLabel = QtWidgets.QLabel(parent=self.addHotmailGroupBox)
        self.groupNameLabel.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupNameLabel.setFont(font)
        self.groupNameLabel.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.groupNameLabel.setObjectName("groupNameLabel")
        self.inputNameGroupHotmail = QtWidgets.QLineEdit(parent=self.addHotmailGroupBox)
        self.inputNameGroupHotmail.setGeometry(QtCore.QRect(150, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputNameGroupHotmail.setFont(font)
        self.inputNameGroupHotmail.setStyleSheet("background-color: #272727;color:#E0E0E0")
        self.inputNameGroupHotmail.setObjectName("inputNameGroupHotmail")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.saveHotmailBtn.clicked.connect(self.saveHotmailData)

    def saveHotmailData(self):
        group_name = self.inputNameGroupHotmail.text()
        hotmail_data = self.inputHotmail.toPlainText().split("\n")
        hotmail_list = [{"hotmail": ua.strip()} for ua in hotmail_data if ua.strip()]
        file_name = utils.HOTMAIL_JSON
        if group_name and hotmail_list:
            # file_name, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save File", "", "JSON Files (*.json)")
            if file_name:
                if not file_name.endswith(".json"):
                    file_name += ".json"

                # Tạo thư mục đích nếu chưa tồn tại
                directory = os.path.dirname(file_name)
                if not os.path.exists(directory):
                    os.makedirs(directory)

                # Kiểm tra và đọc dữ liệu hiện có từ tệp (nếu có)
                if os.path.exists(file_name) and os.path.getsize(file_name) > 0:
                    try:
                        with open(file_name, "r") as file:
                            existing_data = json.load(file)
                    except json.JSONDecodeError:
                        existing_data = []
                else:
                    existing_data = []

                # Tạo dictionary mới cho dữ liệu mới
                new_data = {
                    "groupHotmail": group_name,
                    "listHotmail": hotmail_list
                }

                # Thêm dữ liệu mới vào danh sách dữ liệu hiện có
                existing_data.append(new_data)

                # Ghi lại danh sách dữ liệu vào tệp JSON
                with open(file_name, "w") as file:
                    json.dump(existing_data, file, indent=4, ensure_ascii=False)

                QtWidgets.QMessageBox.information(None, "Thông báo", "Dữ liệu đã được lưu thành công!")
        else:
            QtWidgets.QMessageBox.warning(None, "Cảnh báo", "Vui lòng nhập đầy đủ thông tin trước khi lưu!")




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addHotmailGroupBox.setTitle(_translate("Dialog", "Thêm hotmail"))
        self.saveHotmailBtn.setText(_translate("Dialog", "Lưu"))
        self.groupNameLabel.setText(_translate("Dialog", "Group Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ui_InputHotmail()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
